server:
  port: 0

client:
  url: http://localhost:9090

spring:
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: always
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:ewm
    username: ewm
    password: ewm