spring:
  cloud:
    gateway:
      discovery.locator.enabled: true
      routes:
        - id: user_service_route
          uri: lb://user-service
          predicates:
            - Path=/admin/users/**

        - id: main_service_route
          uri: lb://main-service
          predicates:
            - Path=/**





server:
  port: 8080